### ISSUE TITLE
Cuadro comparativo Jesus Danery Lazo López 

### ISSUE THREAD

**Issue by Dasus2332** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Dasus2332#1]
[Cuadro comparativo Jesus Danery Lazo López.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Dasus2332/files/9473909/Cuadro.comparativo.Jesus.Danery.Lazo.Lopez.pdf)

**Comment by josealfredo79** [comment]
Falta la calificacion

**Comment by josealfredo79** [comment]
Faltan las referencias..

**Comment by josealfredo79** [comment]
Calificacion 15

**Comment by josealfredo79** [comment]
Debe ser un cuadro comparativo

**Comment by josealfredo79** [comment]
Revisado...
